sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install -g codecov
  - npm install

script:
  - npm run lint
  - npm test -- --coverage
  - codecov

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploydoc.sh
  on: 
    branch: master

branches:
  except:
    - /.+-experimental/